// Codex content - organized by category
export const CODEX_CONTENT = {
    en: {
        core: [
            {
                id: 'zoning', title: 'Zoning', icon: ' zoning', category: 'core',
                content: `<h3>Zoning System</h3><p>Each tile in your city has a zone type that determines what can be built there:</p><ul><li><strong>Residential (R)</strong> - Homes for citizens. Higher density homes need more services.</li><li><strong>Commercial (C)</strong> - Stores and businesses. Needs demand and access.</li><li><strong>Industrial (I)</strong> - Factories and workshops. Produces goods and jobs.</li><li><strong>Empty</strong> - Unzoned land. Can be zoned or built on directly.</li></ul><p>Use the <strong>Grid Overlay</strong> (press Z) to see zone boundaries.</p>`
            },
            {
                id: 'utilities', title: 'Utilities', icon: ' water', category: 'core',
                content: `<h3>Utilities Network</h3><p>Your city needs infrastructure to support growth:</p><ul><li><strong>Power</strong> - Generated by power plants. Without power, buildings stop functioning.</li><li><strong>Water</strong> - Pumped from water sources. Required for residential and commercial.</li><li><strong>Sewage</strong> - Treated at sewage plants. Shortage causes pollution.</li><li><strong>Data Grid</strong> - Extends from data hubs. Enables surveillance cameras.</li></ul><p>Build sources (power plants, water pumps) to provide coverage to surrounding tiles.</p>`
            },
            {
                id: 'ops', title: 'Operations', icon: ' operations', category: 'core',
                content: `<h3>Operations Menu</h3><p>Access various management panels through the Operations menu:</p><ul><li><strong>Politics</strong> - Manage policies, appointments, and pressure maps.</li><li><strong>Factions</strong> - Track faction reputation and influence.</li><li><strong>Campaign</strong> - Manage active cases and investigate crimes.</li><li><strong>Citizen</strong> - View individual citizen profiles and needs.</li></ul><p>Press <strong>C</strong> to toggle the Campaign panel.</p>`
            },
            {
                id: 'factions', title: 'Factions', icon: ' factions', category: 'core',
                content: `<h3>Faction System</h3><p>Different groups in your city have varying levels of support and opposition:</p><ul><li><strong>Business Alliance</strong> - Favors low taxes and deregulation.</li><li><strong>Citizens League</strong> - Favors services and quality of life.</li><li><strong>Police Union</strong> - Favors security and surveillance.</li><li><strong>Environmental Group</strong> - Favors green spaces and pollution control.</li></ul><p>Actions affecting factions change their <strong>reputation</strong>. High reputation grants benefits; low reputation causes opposition.</p>`
            },
            {
                id: 'crises', title: 'Crises', icon: ' crisis', category: 'core',
                content: `<h3>Crisis Events</h3><p>Cities face random challenges that test your management skills:</p><ul><li><strong>Power Outage</strong> - Blackout across the city. Restore power quickly!</li><li><strong>Bridge Failure</strong> - Critical transportation link broken.</li><li><strong>Market Crash</strong> - Economic downturn affecting businesses.</li><li><strong>Crime Wave</strong> - Spike in criminal activity.</li></ul><p>Respond to crises through the Crisis Modal. Options affect heat, reputation, and recovery time.</p>`
            },
        ],
        controls: [
            {
                id: 'movement', title: 'Movement', icon: ' movement', category: 'controls',
                content: `<h3>Movement Controls</h3><table class="codex-table"><tr><td><kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd></td><td>Move forward</td></tr><tr><td><kbd>Left Click</kbd></td><td>Interact / Build</td></tr><tr><td><kbd>Right Click + Drag</kbd></td><td>Rotate camera</td></tr><tr><td><kbd>Scroll</kbd></td><td>Zoom in/out</td></tr><tr><td><kbd>Shift + Scroll</kbd></td><td>Pan camera</td></tr></table>`
            },
            {
                id: 'ui', title: 'UI Shortcuts', icon: ' ui', category: 'controls',
                content: `<h3>UI Shortcuts</h3><table class="codex-table"><tr><td><kbd>P</kbd></td><td>Pause / Resume</td></tr><tr><td><kbd>M</kbd></td><td>Toggle Map Screen</td></tr><tr><td><kbd>Z</kbd></td><td>Cycle Zone Overlay</td></tr><tr><td><kbd>Tab</kbd></td><td>Toggle God Mode</td></tr><tr><td><kbd>V</kbd></td><td>Show Citizen Profile</td></tr><tr><td><kbd>C</kbd></td><td>Toggle Campaign Panel</td></tr><tr><td><kbd>S</kbd> + <kbd>Shift</kbd></td><td>Open Shop (Meta)</td></tr><tr><td><kbd>B</kbd> + <kbd>Shift</kbd></td><td>Open Seed Browser</td></tr></table>`
            },
            {
                id: 'modes', title: 'Game Modes', icon: ' modes', category: 'controls',
                content: `<h3>God Mode vs Street Mode</h3><p><strong>Street Mode (default)</strong> - Walk your city, interact with citizens, respond to crises firsthand.</p><p><strong>God Mode</strong> - Bird's eye view for managing infrastructure and monitoring citizens.</p><p>Press <kbd>Tab</kbd> to toggle between modes.</p>`
            },
        ],
        buildings: [
            {
                id: 'residential', title: 'Residential Buildings', icon: '住宅', category: 'buildings',
                content: `<h3>Residential Buildings</h3><p>Homes for your citizens:</p><ul><li><strong>Shack</strong> - Basic shelter (1-2 residents). Low maintenance.</li><li><strong>House</strong> - Standard home (4 residents). Needs water.</li><li><strong>Apartment</strong> - High-density housing (12 residents). Needs power, water, police.</li><li><strong>Luxury</strong> - Premium housing (20 residents). Needs all services, high happiness.</li></ul>`
            },
            {
                id: 'commercial', title: 'Commercial Buildings', icon: ' 商业', category: 'buildings',
                content: `<h3>Commercial Buildings</h3><p>Stores and businesses that generate gold and employment:</p><ul><li><strong>Shop</strong> - Small retail store. Low gold output.</li><li><strong>Market</strong> - Busy marketplace. Moderate gold and demand.</li><li><strong>Office</strong> - Corporate office. High gold, requires educated workforce.</li><li><strong>Hotel</strong> - Tourism hotspot. High gold, high demand.</li></ul>`
            },
            {
                id: 'industrial', title: 'Industrial Buildings', icon: '工业', category: 'buildings',
                content: `<h3>Industrial Buildings</h3><p>Production facilities that generate resources and jobs:</p><ul><li><strong>Farm</strong> - Produces food. Low pollution.</li><li><strong>Lumber Mill</strong> - Produces wood. Moderate pollution.</li><li><strong>Factory</strong> - High production. High pollution and crime risk.</li><li><strong>Power Plant</strong> - Generates electricity. High pollution.</li></ul>`
            },
            {
                id: 'services', title: 'Service Buildings', icon: ' services', category: 'buildings',
                content: `<h3>Service Buildings</h3><p>Essential services for city operations:</p><ul><li><strong>Police Station</strong> - Reduces crime in coverage area.</li><li><strong>Fire Station</strong> - Responds to fires and emergencies.</li><li><strong>Medical Clinic</strong> - Improves citizen health and lifespan.</li><li><strong>School</strong> - Educates citizens.</li><li><strong>Water Pump</strong> - Provides water coverage.</li><li><strong>Sewage Plant</strong> - Treats wastewater. Requires power.</li><li><strong>Data Hub</strong> - Extends data grid. Enables surveillance.</li></ul>`
            },
        ],
        advanced: [
            {
                id: 'demand', title: 'Demand System', icon: ' demand', category: 'advanced',
                content: `<h3>Demand System</h3><p>Commercial and Industrial growth depends on demand:</p><ul><li><strong>R-Commerce</strong> - Driven by residential population.</li><li><strong>R-Industrial</strong> - Driven by residential population and jobs.</li><li><strong>C-Commercial</strong> - Driven by commercial success and tourism.</li><li><strong>I-Industrial</strong> - Driven by industrial capacity and exports.</li></ul>`
            },
            {
                id: 'heat', title: 'Heat & Exposure', icon: ' heat', category: 'advanced',
                content: `<h3>Heat Management</h3><p>Heat represents attention from rivals and authorities:</p><ul><li><strong>Low Heat</strong> - No attention. Operate freely.</li><li><strong>Medium Heat</strong> - Increased scrutiny. Police checkpoints.</li><li><strong>High Heat</strong> - Active investigation. Rival pressure.</li><li><strong>Critical Heat</strong> - Major crisis. Potential intervention.</li></ul>`
            },
            {
                id: 'progression', title: 'Victory Progression', icon: ' progression', category: 'advanced',
                content: `<h3>Victory Types</h3><p>Complete these paths to victory:</p><ul><li><strong>Military</strong> - Control 50% of city with police coverage.</li><li><strong>Economic</strong> - Accumulate 100,000 gold.</li><li><strong>Cultural</strong> - Achieve 90% citizen happiness for 50 days.</li><li><strong>Technological</strong> - Complete 10 cases with high intel.</li></ul>`
            },
            {
                id: 'campaign', title: 'Campaign System', icon: ' campaign', category: 'advanced',
                content: `<h3>Campaign (Case Files)</h3><p>Investigate crimes and complete objectives:</p><ul><li><strong>Missing Person</strong> - Find a missing citizen.</li><li><strong>Corruption</strong> - Expose corrupt officials.</li><li><strong>Extortion</strong> - Stop a crime ring.</li><li><strong>Smuggling</strong> - Interdict illegal goods.</li></ul>`
            },
        ],
    }
};
