// Codex / Help System for Beta Release
// Provides in-game reference for mechanics, controls, and concepts

// Codex content - organized by category
const CODEX_CONTENT = {
    en: {
        // Core Concepts
        core: [
            {
                id: 'zoning',
                title: 'Zoning',
                icon: ' zoning',
                category: 'core',
                content: `
                    <h3>Zoning System</h3>
                    <p>Each tile in your city has a zone type that determines what can be built there:</p>
                    <ul>
                        <li><strong>Residential (R)</strong> - Homes for citizens. Higher density homes need more services.</li>
                        <li><strong>Commercial (C)</strong> - Stores and businesses. Needs demand and access.</li>
                        <li><strong>Industrial (I)</strong> - Factories and workshops. Produces goods and jobs.</li>
                        <li><strong>Empty</strong> - Unzoned land. Can be zoned or built on directly.</li>
                    </ul>
                    <p>Use the <strong>Grid Overlay</strong> (press Z) to see zone boundaries.</p>
                `
            },
            {
                id: 'utilities',
                title: 'Utilities',
                icon: ' water',
                category: 'core',
                content: `
                    <h3>Utilities Network</h3>
                    <p>Your city needs infrastructure to support growth:</p>
                    <ul>
                        <li><strong>Power</strong> - Generated by power plants. Without power, buildings stop functioning.</li>
                        <li><strong>Water</strong> - Pumped from water sources. Required for residential and commercial.</li>
                        <li><strong>Sewage</strong> - Treated at sewage plants. Shortage causes pollution.</li>
                        <li><strong>Data Grid</strong> - Extends from data hubs. Enables surveillance cameras.</li>
                    </ul>
                    <p>Build sources (power plants, water pumps) to provide coverage to surrounding tiles.</p>
                `
            },
            {
                id: 'ops',
                title: 'Operations',
                icon: ' operations',
                category: 'core',
                content: `
                    <h3>Operations Menu</h3>
                    <p>Access various management panels through the Operations menu:</p>
                    <ul>
                        <li><strong>Politics</strong> - Manage policies, appointments, and pressure maps.</li>
                        <li><strong>Factions</strong> - Track faction reputation and influence.</li>
                        <li><strong>Campaign</strong> - Manage active cases and investigate crimes.</li>
                        <li><strong>Citizen</strong> - View individual citizen profiles and needs.</li>
                    </ul>
                    <p>Press <strong>C</strong> to toggle the Campaign panel.</p>
                `
            },
            {
                id: 'factions',
                title: 'Factions',
                icon: ' factions',
                category: 'core',
                content: `
                    <h3>Faction System</h3>
                    <p>Different groups in your city have varying levels of support and opposition:</p>
                    <ul>
                        <li><strong>Business Alliance</strong> - Favors low taxes and deregulation.</li>
                        <li><strong>Citizens League</strong> - Favors services and quality of life.</li>
                        <li><strong>Police Union</strong> - Favors security and surveillance.</li>
                        <li><strong>Environmental Group</strong> - Favors green spaces and pollution control.</li>
                    </ul>
                    <p>Actions affecting factions change their <strong>reputation</strong>. High reputation grants benefits; low reputation causes opposition.</p>
                `
            },
            {
                id: 'crises',
                title: 'Crises',
                icon: ' crisis',
                category: 'core',
                content: `
                    <h3>Crisis Events</h3>
                    <p>Cities face random challenges that test your management skills:</p>
                    <ul>
                        <li><strong>Power Outage</strong> - Blackout across the city. Restore power quickly!</li>
                        <li><strong>Bridge Failure</strong> - Critical transportation link broken.</li>
                        <li><strong>Market Crash</strong> - Economic downturn affecting businesses.</li>
                        <li><strong>Crime Wave</strong> - Spike in criminal activity.</li>
                    </ul>
                    <p>Respond to crises through the Crisis Modal. Options affect heat, reputation, and recovery time.</p>
                `
            }
        ],

        // Controls
        controls: [
            {
                id: 'movement',
                title: 'Movement',
                icon: ' movement',
                category: 'controls',
                content: `
                    <h3>Movement Controls</h3>
                    <table class="codex-table">
                        <tr><td><kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd></td><td>Move forward</td></tr>
                        <tr><td><kbd>Left Click</kbd></td><td>Interact / Build</td></tr>
                        <tr><td><kbd>Right Click + Drag</kbd></td><td>Rotate camera</td></tr>
                        <tr><td><kbd>Scroll</kbd></td><td>Zoom in/out</td></tr>
                        <tr><td><kbd>Shift + Scroll</kbd></td><td>Pan camera</td></tr>
                    </table>
                `
            },
            {
                id: 'ui',
                title: 'UI Shortcuts',
                icon: ' ui',
                category: 'controls',
                content: `
                    <h3>UI Shortcuts</h3>
                    <table class="codex-table">
                        <tr><td><kbd>P</kbd></td><td>Pause / Resume</td></tr>
                        <tr><td><kbd>M</kbd></td><td>Toggle Map Screen</td></tr>
                        <tr><td><kbd>Z</kbd></td><td>Cycle Zone Overlay</td></tr>
                        <tr><td><kbd>Tab</kbd></td><td>Toggle God Mode</td></tr>
                        <tr><td><kbd>V</kbd></td><td>Show Citizen Profile</td></tr>
                        <tr><td><kbd>C</kbd></td><td>Toggle Campaign Panel</td></tr>
                        <tr><td><kbd>S</kbd> + <kbd>Shift</kbd></td><td>Open Shop (Meta)</td></tr>
                        <tr><td><kbd>B</kbd> + <kbd>Shift</kbd></td><td>Open Seed Browser</td></tr>
                    </table>
                `
            },
            {
                id: 'modes',
                title: 'Game Modes',
                icon: ' modes',
                category: 'controls',
                content: `
                    <h3>God Mode vs Street Mode</h3>
                    <p><strong>Street Mode (default)</strong> - Walk your city, interact with citizens, respond to crises firsthand. View from a third-person perspective.</p>
                    <p><strong>God Mode</strong> -俯瞰城市，管理基础设施，监控公民。Use the map overlay to see demand and zone boundaries.</p>
                    <p>Press <kbd>Tab</kbd> to toggle between modes.</p>
                `
            }
        ],

        // Buildings
        buildings: [
            {
                id: 'residential',
                title: 'Residential Buildings',
                icon: '住宅',
                category: 'buildings',
                content: `
                    <h3>Residential Buildings</h3>
                    <p>Homes for your citizens. Higher population requires more services:</p>
                    <ul>
                        <li><strong>Shack</strong> - Basic shelter (1-2 residents). Low maintenance.</li>
                        <li><strong>House</strong> - Standard home (4 residents). Needs water.</li>
                        <li><strong>Apartment</strong> - High-density housing (12 residents). Needs power, water, police.</li>
                        <li><strong>Luxury</strong> - Premium housing (20 residents). Needs all services, high happiness.</li>
                    </ul>
                `
            },
            {
                id: 'commercial',
                title: 'Commercial Buildings',
                icon: ' 商业',
                category: 'buildings',
                content: `
                    <h3>Commercial Buildings</h3>
                    <p>Stores and businesses that generate gold and employment:</p>
                    <ul>
                        <li><strong>Shop</strong> - Small retail store. Low gold output.</li>
                        <li><strong>Market</strong> - Busy marketplace. Moderate gold and demand.</li>
                        <li><strong>Office</strong> - Corporate office. High gold, requires educated workforce.</li>
                        <li><strong>Hotel</strong> - Tourism hotspot. High gold, high demand.</li>
                    </ul>
                `
            },
            {
                id: 'industrial',
                title: 'Industrial Buildings',
                icon: '工业',
                category: 'buildings',
                content: `
                    <h3>Industrial Buildings</h3>
                    <p>Production facilities that generate resources and jobs:</p>
                    <ul>
                        <li><strong>Farm</strong> - Produces food. Low pollution.</li>
                        <li><strong>Lumber Mill</strong> - Produces wood. Moderate pollution.</li>
                        <li><strong>Factory</strong> - High production. High pollution and crime risk.</li>
                        <li><strong>Power Plant</strong> - Generates electricity. High pollution.</li>
                    </ul>
                `
            },
            {
                id: 'services',
                title: 'Service Buildings',
                icon: ' services',
                category: 'buildings',
                content: `
                    <h3>Service Buildings</h3>
                    <p>Essential services for city operations:</p>
                    <ul>
                        <li><strong>Police Station</strong> - Reduces crime in coverage area. Dispatches officers.</li>
                        <li><strong>Fire Station</strong> - Responds to fires and emergencies.</li>
                        <li><strong>Medical Clinic</strong> - Improves citizen health and lifespan.</li>
                        <li><strong>School</strong> - Educates citizens. Improves job placement.</li>
                        <li><strong>Water Pump</strong> - Provides water coverage. Prevents pollution.</li>
                        <li><strong>Sewage Plant</strong> - Treats wastewater. Requires power.</li>
                        <li><strong>Data Hub</strong> - Extends data grid. Enables surveillance.</li>
                    </ul>
                `
            }
        ],

        // Advanced
        advanced: [
            {
                id: 'demand',
                title: 'Demand System',
                icon: ' demand',
                category: 'advanced',
                content: `
                    <h3>Demand System</h3>
                    <p>Commercial and Industrial growth depends on demand:</p>
                    <ul>
                        <li><strong>R-Commerce</strong> - Driven by residential population.</li>
                        <li><strong>R-Industrial</strong> - Driven by residential population and jobs.</li>
                        <li><strong>C-Commercial</strong> - Driven by commercial success and tourism.</li>
                        <li><strong>I-Industrial</strong> - Driven by industrial capacity and exports.</li>
                    </ul>
                    <p>Build residential to increase base demand. Provide services to boost growth.</p>
                `
            },
            {
                id: 'heat',
                title: 'Heat & Exposure',
                icon: ' heat',
                category: 'advanced',
                content: `
                    <h3>Heat Management</h3>
                    <p>Heat represents attention from rivals and authorities:</p>
                    <ul>
                        <li><strong>Low Heat</strong> - No attention. Operate freely.</li>
                        <li><strong>Medium Heat</strong> - Increased scrutiny. Police checkpoints.</li>
                        <li><strong>High Heat</strong> - Active investigation. Rival pressure.</li>
                        <li><strong>Critical Heat</strong> - Major crisis. Potential intervention.</li>
                    </ul>
                    <p>Heat builds from crime, controversial policies, and rival activity. Reduce by completing cases or improving sentiment.</p>
                `
            },
            {
                id: 'progression',
                title: 'Victory Progression',
                icon: ' progression',
                category: 'advanced',
                content: `
                    <h3>Victory Types</h3>
                    <p>Complete these paths to victory:</p>
                    <ul>
                        <li><strong>Military</strong> - Control 50% of city with police coverage.</li>
                        <li><strong>Economic</strong> - Accumulate 100,000 gold.</li>
                        <li><strong>Cultural</strong> - Achieve 90% citizen happiness for 50 days.</li>
                        <li><strong>Technological</strong> - Complete 10 cases with high intel.</li>
                    </ul>
                    <p>Most cities achieve multiple victory types simultaneously.</p>
                `
            },
            {
                id: 'campaign',
                title: 'Campaign System',
                icon: ' campaign',
                category: 'advanced',
                content: `
                    <h3>Campaign (Case Files)</h3>
                    <p>Investigate crimes and complete objectives:</p>
                    <ul>
                        <li><strong>Missing Person</strong> - Find a missing citizen.</li>
                        <li><strong>Corruption</strong> - Expose corrupt officials.</li>
                        <li><strong>Extortion</strong> - Stop a crime ring.</li>
                        <li><strong>Smuggling</strong> - Interdict illegal goods.</li>
                    </ul>
                    <p>Each case has multiple chapters and outcomes. Choices affect reputation and heat.</p>
                `
            }
        ]
    }
};

/**
 * Codex UI Manager
 */
export class CodexUI {
    constructor(game) {
        this.game = game;
        this.currentCategory = 'core';
        this.currentSearch = '';
        this.isOpen = false;
        this.elements = {};
        this.init();
    }

    /**
     * Initialize UI elements
     */
    init() {
        // Create codex container
        const container = document.createElement('div');
        container.id = 'codex-overlay';
        container.className = 'overlay hidden';
        container.style.zIndex = '10000';
        container.innerHTML = `
            <div class="overlay-content" style="max-width: 900px; max-height: 90vh; overflow: hidden; display: flex; flex-direction: column;">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
                    <h2 style="margin: 0;">City Codex</h2>
                    <button class="btn btn-secondary" id="codex-close-btn" style="padding: 8px 16px;">
                        <svg width="16" height="16" viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>
                    </button>
                </div>

                <div style="display: flex; gap: 16px; flex: 1; overflow: hidden;">
                    <!-- Categories Sidebar -->
                    <div style="width: 180px; flex-shrink: 0; overflow-y: auto; border-right: 1px solid rgba(255,255,255,0.1); padding-right: 16px;">
                        <div style="margin-bottom: 16px;">
                            <input type="text" id="codex-search" placeholder="Search topics..." style="width: 100%; padding: 10px; background: #1a2634; border: 1px solid rgba(255,255,255,0.1); color: white; border-radius: 4px; box-sizing: border-box;">
                        </div>
                        <div style="display: flex; flex-direction: column; gap: 4px;">
                            <button class="category-btn active" data-category="core" style="padding: 10px; text-align: left; background: #2f5f4a; border: none; color: white; border-radius: 4px; cursor: pointer;">
                                <span>Core Concepts</span>
                            </button>
                            <button class="category-btn" data-category="controls" style="padding: 10px; text-align: left; background: #1a2634; border: 1px solid rgba(255,255,255,0.1); color: white; border-radius: 4px; cursor: pointer;">
                                <span>Controls</span>
                            </button>
                            <button class="category-btn" data-category="buildings" style="padding: 10px; text-align: left; background: #1a2634; border: 1px solid rgba(255,255,255,0.1); color: white; border-radius: 4px; cursor: pointer;">
                                <span>Buildings</span>
                            </button>
                            <button class="category-btn" data-category="advanced" style="padding: 10px; text-align: left; background: #1a2634; border: 1px solid rgba(255,255,255,0.1); color: white; border-radius: 4px; cursor: pointer;">
                                <span>Advanced</span>
                            </button>
                        </div>
                    </div>

                    <!-- Content Area -->
                    <div style="flex: 1; overflow-y: auto; padding-left: 16px;">
                        <div id="codex-content"></div>
                    </div>
                </div>

                <div style="margin-top: 16px; text-align: center; font-size: 12px; color: #888;">
                    <span>Press <kbd>?</kbd> to open/close this guide</span>
                </div>
            </div>
        `;

        document.body.appendChild(container);
        this.container = container;

        // Cache elements
        this.elements = {
            content: document.getElementById('codex-content'),
            search: document.getElementById('codex-search'),
            closeBtn: document.getElementById('codex-close-btn'),
            categoryBtns: container.querySelectorAll('.category-btn')
        };

        // Setup event listeners
        this.elements.closeBtn.addEventListener('click', () => this.close());
        this.elements.search.addEventListener('input', (e) => this.filterContent(e.target.value));
        this.elements.categoryBtns.forEach(btn => {
            btn.addEventListener('click', (e) => this.selectCategory(e.target.dataset.category));
        });

        // Keyboard shortcut
        document.addEventListener('keydown', (e) => {
            if (!this.isOpen && e.key === '?') {
                e.preventDefault();
                this.open();
            } else if (this.isOpen && e.key === 'Escape') {
                this.close();
            }
        });
    }

    /**
     * Open codex
     */
    open() {
        this.isOpen = true;
        this.container.classList.remove('hidden');
        this.updateContent(this.currentCategory);
        this.elements.search.value = '';
    }

    /**
     * Close codex
     */
    close() {
        this.isOpen = false;
        this.container.classList.add('hidden');
    }

    /**
     * Toggle codex visibility
     */
    toggle() {
        if (this.isOpen) {
            this.close();
        } else {
            this.open();
        }
    }

    /**
     * Select category
     */
    selectCategory(category) {
        this.currentCategory = category;
        this.updateContent(category);
    }

    /**
     * Filter content by search
     */
    filterContent(search) {
        this.currentSearch = search.toLowerCase();
        this.updateContent(this.currentCategory);
    }

    /**
     * Update content display
     */
    updateContent(category) {
        const contentContainer = this.elements.content;
        const entries = this.getEntries(category);

        if (entries.length === 0) {
            contentContainer.innerHTML = `
                <div style="text-align: center; padding: 40px 20px;">
                    <p style="color: #888;">No entries found in this category.</p>
                </div>
            `;
            return;
        }

        contentContainer.innerHTML = entries.map(entry => `
            <div class="codex-entry" style="background: rgba(255,255,255,0.03); padding: 20px; border-radius: 8px; margin-bottom: 20px; border: 1px solid rgba(255,255,255,0.05);">
                <h3 style="margin-top: 0; color: #54d3ff;">
                    <span style="font-size: 24px; margin-right: 10px;">${entry.icon}</span>
                    ${entry.title}
                </h3>
                <div class="codex-text">${entry.content}</div>
            </div>
        `).join('');

        // Add CSS for codex
        this.ensureStyles();
    }

    /**
     * Get entries for a category
     */
    getEntries(category) {
        const content = CODEX_CONTENT.en;
        const entries = content[category] || [];

        if (!this.currentSearch) {
            return entries;
        }

        return entries.filter(entry =>
            entry.title.toLowerCase().includes(this.currentSearch) ||
            entry.content.toLowerCase().includes(this.currentSearch)
        );
    }

    /**
     * Add codex CSS if not present
     */
    ensureStyles() {
        const styleId = 'codex-styles';
        if (document.getElementById(styleId)) return;

        const style = document.createElement('style');
        style.id = styleId;
        style.textContent = `
            .codex-entry h3 {
                color: #54d3ff;
            }
            .codex-entry ul {
                margin: 10px 0 15px 20px;
            }
            .codex-entry li {
                margin-bottom: 5px;
            }
            .codex-table {
                width: 100%;
                border-collapse: collapse;
                margin: 10px 0;
            }
            .codex-table td {
                padding: 8px 12px;
                border-bottom: 1px solid rgba(255,255,255,0.1);
            }
            .codex-table td:first-child {
                text-align: right;
                font-family: monospace;
                color: #54d3ff;
            }
            .codex-table td:last-child {
                color: #e6f2ff;
            }
        `;
        document.head.appendChild(style);
    }
}

/**
 * Create codex UI instance
 */
export function createCodexUI(game) {
    return new CodexUI(game);
}